### ISSUE TITLE
做的挺好的，看到了就提几个小意见

### ISSUE THREAD

**Issue by luzhixing12345** [de3BDJMH/Time#1]
1. `main.py`还是有点太过冗长了，我看到你把所有按钮封装在了一个APP类里面，而且重复甚多，tk我没用过但我觉得应该界面切换可以提出来每一个界面的，或者设计一个基类继承它
2. 别的不说，`month.py`你不觉得写的太复杂了么，数组可以解决的问题不至于这么多ifelse吧
3. `__pycache__`是python编译产生的字节码文件，不建议放到GitHub上，可以了解一下gitignore的使用
4. README文件要写的规范一些，加一些执行的截图或者文字描述会对看你项目代码的人有很大帮助
5. 做的挺好的，加油~

**Comment by de3BDJMH** [comment]
嗯，谢谢指点，自己也是初学，没了解这么多，不过有大家的指点一定会努力哒
